Fixed a small typo ("om" to "from")
nunit/docs pull request #521
Opened 2020-10-30 16:20 UTC by tupacko

2020-10-30 16:20 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/nunit/docs?pullRequest=521) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nunit/docs?pullRequest=521) before we can accept your contribution.<br/><br/>:x: tupacko [sign now](https://cla.dotnetfoundation.org/nunit/docs?pullRequest=521)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nunit/docs?pullRequest=521) it.</sub>

2020-10-30 16:24 UTC, SeanKilleen requested changes
Nice catch! I suggested a minor change to make the phrasing more correct.

2020-10-30 16:24 UTC, SeanKilleen commented on docs/articles/vs-test-adapter/Index.md
> +The current release is designed to work with Visual Studio 2012, 2013, 2015, 2017 and 2019. Some features are not available under VS2012 RTM. It also works from command line using either vstest.conso
```suggestion
The current release is designed to work with Visual Studio 2012, 2013, 2015, 2017 and 2019. Some features are not available under VS2012 RTM. It also works from the command line using either vstest.console or dotnet test, and is also used by JetBrains ReSharper for Visual Studio and Rider IDE, and their corresponding command line tool.
```

2020-10-31 10:51 UTC, mikkelbu approved these changes

2020-11-02 15:05 UTC, tupacko reviewed
I also included the suggested changes.

2020-11-04 12:46 UTC, SeanKilleen commented
Very nice -- thank you @tupacko!

2020-11-04 12:46 UTC, merged